(() => {
const C=window.EXAM_CONFIG,K=window.ANSWER_KEY||[], $=s=>document.querySelector(s);
const views=['loginView','lobbyView','examView','resultView','adminView']; let user=null,answers=[],doubts=[],remaining=0,tick=null,lastResult=null,examActive=false,violations=0,visibilityTimer=null,pdfUrl=null;
function show(id){views.forEach(v=>$('#'+v).classList.toggle('hidden',v!==id));$('#logoutBtn').classList.toggle('hidden',id==='loginView'||id==='examView')}
function fa(n){return new Intl.NumberFormat('fa-IR',{maximumFractionDigits:2}).format(n)}
function msg(el,text,type='notice'){el.innerHTML=text?`<div class="notice ${type}">${text}</div>`:''}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#appTitle').textContent=C.appTitle;$('#examName').textContent=C.examTitle;$('#durationText').textContent=fa(C.durationMinutes);
function preparePdf(){try{if(window.PDF_BASE64){const raw=atob(window.PDF_BASE64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);pdfUrl=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}))}else pdfUrl=C.pdfFile}catch{pdfUrl=C.pdfFile}$('#pdfDownload').href=pdfUrl;$('#pdfDownload').download='question1.pdf';$('#pdfObject').data=pdfUrl;$('#pdfFallback').href=pdfUrl}
preparePdf();
function normalizeDigits(value){return String(value).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d))}
$('#loginForm').onsubmit=e=>{e.preventDefault();let u=normalizeDigits($('#username').value).trim().toLowerCase(),p=normalizeDigits($('#password').value).trim();user=C.accounts.find(a=>a.username.toLowerCase()===u&&normalizeDigits(a.password)===p);if(!user)return msg($('#loginMsg'),'نام کاربری یا رمز عبور نادرست است. لطفاً دوباره بررسی کنید.','error');sessionStorage.setItem('examSession',JSON.stringify(user));route()};
function route(){if(!user)return show('loginView');if(user.role==='admin'){renderAdmin();return show('adminView')}let used=localStorage.getItem(`attempt:${C.examId}:${user.username}`);if(!C.examEnabled)return msg($('#lobbyMsg'),'این آزمون در حال حاضر غیرفعال است.','error'),show('lobbyView');if(used&&user.role==='student'){msg($('#lobbyMsg'),'شما قبلاً در این آزمون شرکت کرده‌اید.','error');$('#startBtn').disabled=true}else{$('#startBtn').disabled=!$('#rulesAccept').checked;msg($('#lobbyMsg'),user.role==='tester'?'حساب تست فعال است و امکان شرکت چندباره دارد.':'پس از شروع، زمان‌سنج متوقف نخواهد شد.')}show('lobbyView')}
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('examSession');user=null;show('loginView')};
$('#rulesAccept').onchange=()=>{$('#startBtn').disabled=!$('#rulesAccept').checked};
$('#startBtn').onclick=()=>{if(!C.questionCount||K.length!==C.questionCount)return msg($('#lobbyMsg'),'آزمون هنوز به‌طور کامل تنظیم نشده است.','error');answers=Array(C.questionCount).fill(null);doubts=Array(C.questionCount).fill(false);remaining=C.durationMinutes*60;violations=0;examActive=true;$('#violationBanner').classList.add('hidden');if(user.role==='student')localStorage.setItem(`attempt:${C.examId}:${user.username}`,'started');renderAnswers();show('examView');updateTimer();tick=setInterval(()=>{remaining--;updateTimer();if(remaining<=0)finish()},1000)};
function renderAnswers(){const start=C.questionStartNumber||1;$('#answerUi').innerHTML=`<div class="answer-list">${answers.map((a,i)=>`<div class="answer-row ${a?'answered':''} ${doubts[i]?'doubt':''}"><b class="question-number">${fa(start+i)}</b><div class="row-options">${[1,2,3,4].map(o=>`<button class="option ${a===o?'active':''}" data-i="${i}" data-o="${o}" title="گزینه ${o}">${fa(o)}</button>`).join('')}</div><button class="row-action clear-answer" data-i="${i}" ${a?'':'disabled'}>پاک کردن</button><button class="row-action doubt-answer ${doubts[i]?'active':''}" data-i="${i}">${doubts[i]?'شک‌دار ✓':'شک‌دار'}</button></div>`).join('')}</div>`;$('#currentLabel').textContent=`شک‌دار: ${fa(doubts.filter(Boolean).length)}`;$('#answeredCount').textContent=`پاسخ‌داده: ${fa(answers.filter(Boolean).length)}`;document.querySelectorAll('.row-options [data-o]').forEach(b=>b.onclick=()=>{const i=+b.dataset.i,o=+b.dataset.o;answers[i]=answers[i]===o?null:o;renderAnswers()});document.querySelectorAll('.clear-answer').forEach(b=>b.onclick=()=>{answers[+b.dataset.i]=null;renderAnswers()});document.querySelectorAll('.doubt-answer').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;doubts[i]=!doubts[i];renderAnswers()})}
function updateTimer(){let m=Math.floor(remaining/60),s=remaining%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
$('#finishBtn').onclick=()=>$('#confirmModal').classList.remove('hidden');$('#cancelFinish').onclick=()=>$('#confirmModal').classList.add('hidden');$('#confirmFinish').onclick=finish;
function finish(){if(!examActive&&!tick)return;examActive=false;if(visibilityTimer)clearTimeout(visibilityTimer);if(tick)clearInterval(tick);tick=null;$('#confirmModal').classList.add('hidden');$('#leaveWarning').classList.add('hidden');let correct=0,wrong=0;answers.forEach((a,i)=>{if(a===null)return;if(a===K[i])correct++;else wrong++});let blank=C.questionCount-correct-wrong,raw=correct/C.questionCount*100,neg=Math.max(0,(correct-wrong*C.negativeMarking.wrongPenalty)/C.questionCount*100);lastResult={version:1,examId:C.examId,examTitle:C.examTitle,username:user.username,displayName:user.displayName,submittedAt:new Date().toISOString(),correct,wrong,blank,total:C.questionCount,rawPercent:+raw.toFixed(2),negativePercent:+neg.toFixed(2),exitWarnings:violations};if(user.role==='student')localStorage.setItem(`attempt:${C.examId}:${user.username}`,'finished');displayResult()}
function displayResult(){let r=lastResult;$('#negativePercent').textContent=fa(r.negativePercent)+'٪';$('#rawPercent').textContent=fa(r.rawPercent)+'٪';$('#counts').textContent=`${fa(r.correct)} / ${fa(r.total)}`;$('#resultIdentity').textContent=`${r.displayName} — ${r.examTitle}`;$('#resultDetails').textContent=`صحیح: ${fa(r.correct)} | غلط: ${fa(r.wrong)} | بدون پاسخ: ${fa(r.blank)} | هشدار خروج: ${fa(r.exitWarnings||0)}`;show('resultView')}
$('#downloadResult').onclick=()=>{let blob=new Blob([JSON.stringify(lastResult,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`result-${lastResult.username}-${C.examId}.json`;a.click();URL.revokeObjectURL(a.href)};$('#backBtn').onclick=route;
function getResults(){try{return JSON.parse(localStorage.getItem('importedResults')||'[]')}catch{return[]}}
function renderAdmin(){let rs=getResults();$('#resultCount').textContent=fa(rs.length);$('#avgNegative').textContent=fa(rs.length?rs.reduce((a,r)=>a+r.negativePercent,0)/rs.length:0)+'٪';$('#avgRaw').textContent=fa(rs.length?rs.reduce((a,r)=>a+r.rawPercent,0)/rs.length:0)+'٪';$('#resultsBody').innerHTML=rs.length?rs.map(r=>`<tr><td>${esc(r.displayName)} (${esc(r.username)})</td><td>${new Date(r.submittedAt).toLocaleString('fa-IR')}</td><td>${fa(r.correct)}</td><td>${fa(r.wrong)}</td><td>${fa(r.blank)}</td><td>${fa(r.negativePercent)}٪</td><td>${fa(r.rawPercent)}٪</td></tr>`).join(''):'<tr><td colspan="7">هنوز نتیجه‌ای وارد نشده است.</td></tr>'}
$('#importResult').onchange=async e=>{let rs=getResults();for(const f of e.target.files){try{let r=JSON.parse(await f.text());if(r.examId&&Number.isFinite(r.negativePercent)&&!rs.some(x=>x.username===r.username&&x.submittedAt===r.submittedAt))rs.push(r)}catch{}}localStorage.setItem('importedResults',JSON.stringify(rs));renderAdmin();e.target.value=''};
$('#clearResults').onclick=()=>{if(confirm('همه نتایج محلی پاک شوند؟')){localStorage.removeItem('importedResults');renderAdmin()}};
function registerExitWarning(){if(!examActive)return;violations++;$('#violationBanner').textContent=`هشدار: خروج از محیط آزمون ثبت شد. تعداد هشدارها: ${fa(violations)}`;$('#violationBanner').classList.remove('hidden');$('#leaveWarning').classList.remove('hidden')}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&examActive){visibilityTimer=setTimeout(()=>{if(document.hidden&&examActive)registerExitWarning()},4000)}else if(visibilityTimer){clearTimeout(visibilityTimer);visibilityTimer=null}});
window.addEventListener('beforeunload',e=>{if(examActive){e.preventDefault();e.returnValue=''}});
$('#returnExam').onclick=()=>{$('#leaveWarning').classList.add('hidden')};
try{user=JSON.parse(sessionStorage.getItem('examSession'))}catch{} route();
})();
